name: Add Bundler Platforms

on:
  workflow_dispatch: # Run manually from the Actions tab

jobs:
  add-platforms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Bundler
        run: gem install bundler

      - name: Add common platforms to Gemfile.lock
        run: |
          bundle lock --add-platform x86_64-linux
          bundle lock --add-platform x64-mingw-ucrt
          bundle lock --add-platform x86_64-darwin

      - name: Commit and push updated Gemfile.lock
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add Gemfile.lock
          git commit -m "Add multi-platform support to Gemfile.lock"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
