name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # or 'master', adjust to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production

    steps:
      - uses: actions/checkout@v4

      - name: Install image processing dependencies # tiff, svg2, heif, gif, exif are optional.
        run: |
            sudo apt-get update
            sudo apt-get install -y \
            libvips-dev \
            imagemagick \
            libjpeg-dev \
            libpng-dev \
            libwebp-dev \
            libavif-dev \
            libtiff-dev \
            librsvg2-dev \
            libheif-dev \
            libgif-dev \
            libexif-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # adjust if needed
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # or ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site
